development:
  adapter: sqlite3
  database: db/development_meme_generator.sqlite3


test:
  adapter: sqlite3
  database: db/test_meme_generator.sqlite3

production:
  adapter: sqlite3
  database: db/production_meme_generator.sqlite3